### ISSUE TITLE
Expression too long issues in Xcode 6.3 / Swift 1.2

### ISSUE THREAD

**Issue by czeluff** [thoughtbot/Argo#106] opened 2015-04-12 17:46 UTC
Apologies for the enormous code block - figure I should just show this in its entirety. I've seen previous issues related to this need to break up the object into multiple pieces to make the 'decode' function work properly. However, I also appear to be having an issue with the curried 'create' function - it seems to be giving up around "item3" due to too many parameters.

Some people have shown potential fixes by breaking up 'decode' [like so](https://github.com/thoughtbot/Argo/issues/5#issuecomment-78961913) but this is not compiling for me, either.

If I need to break up the object into multiple pieces, I'll have to. Though this can be pretty annoying, requiring more curried 'create' functions.

```swift
public struct RawStats {
    let assists: Int
    let barracksKilled: Int
    let championsKilled: Int
    let combatPlayerScore: Int
    let consumablesPurchased: Int
    let damageDealtPlayer: Int
    let doubleKills: Int
    let firstBlood: Int
    let gold: Int
    let goldEarned: Int
    let goldSpent: Int
    let item0: Int
    let item1: Int
    let item2: Int
    let item3: Int
    let item4: Int
    let item5: Int
    let item6: Int
    let itemsPurchased: Int
    let killingSprees: Int
    let largestCriticalStrike: Int
    let largestKillingSpree: Int
    let largestMultiKill: Int
    let legendaryItemsCreated: Int
    let level: Int
    let magicDamageDealtPlayer: Int
    let magicDamageDealtToChampions: Int
    let magicDamageTaken: Int
    let minionsDenied: Int
    let minionsKilled: Int
    let neutralMinionsKilled: Int
    let neutralMinionsKilledEnemyJungle: Int
    let neutralMinionsKilledYourJungle: Int
    let nexusKilled: Bool
    let nodeCapture: Int
    let nodeCaptureAssist: Int
    let nodeNeutralize: Int
    let nodeNeutralizeAssist: Int
    let numDeaths: Int
    let numItemsBought: Int
    let objectivePlayerScore: Int
    let pentaKills: Int
    let physicalDamageDealtPlayer: Int
    let physicalDamageDealtToChampions: Int
    let physicalDamageTaken: Int
    let playerPosition: Int
    let playerRole: Int
    let quadraKills: Int
    let sightWardsBought: Int
    let spell1Cast: Int
    let spell2Cast: Int
    let spell3Cast: Int
    let spell4Cast: Int
    let summonSpell1Cast: Int
    let summonSpell2Cast: Int
    let superMonsterKilled: Int
    let team: Int
    let teamObjective: Int
    let timePlayed: Int
    let totalDamageDealt: Int
    let totalDamageDealtToChampions: Int
    let totalDamageTaken: Int
    let totalHeal: Int
    let totalPlayerScore: Int
    let totalScoreRank: Int
    let totalTimeCrowdControlDealt: Int
    let totalUnitsHealed: Int
    let tripleKills: Int
    let trueDamageDealtPlayer: Int
    let trueDamageDealtToChampions: Int
    let trueDamageTaken: Int
    let turretsKilled: Int
    let unrealKills: Int
    let victoryPointTotal: Int
    let visionWardsBought: Int
    let wardKilled: Int
    let wardPlaced: Int
    let win	: Bool
}

extension RawStats: JSONDecodable {
    static func create(assists: Int)(barracksKilled: Int)(championsKilled: Int)(combatPlayerScore: Int)(consumablesPurchased: Int)(damageDealtPlayer: Int)(doubleKills: Int)(firstBlood: Int)(gold: Int)(goldEarned: Int)(goldSpent: Int)(item0: Int)(item1: Int)(item2: Int)(item3: Int)(item4: Int)(item5: Int)(item6: Int)(itemsPurchased: Int)(killingSprees: Int)(largestCriticalStrike: Int)(largestKillingSpree: Int)(largestMultiKill: Int)(legendaryItemsCreated: Int)(level: Int)(magicDamageDealtPlayer: Int)(magicDamageDealtToChampions: Int)(magicDamageTaken: Int)(minionsDenied: Int)(minionsKilled: Int)(neutralMinionsKilled: Int)(neutralMinionsKilledEnemyJungle: Int)(neutralMinionsKilledYourJungle: Int)(nexusKilled: Bool)(nodeCapture: Int)(nodeCaptureAssist: Int)(nodeNeutralize: Int)(nodeNeutralizeAssist: Int)(numDeaths: Int)(numItemsBought: Int)(objectivePlayerScore: Int)(pentaKills: Int)(physicalDamageDealtPlayer: Int)(physicalDamageDealtToChampions: Int)(physicalDamageTaken: Int)(playerPosition: Int)(playerRole: Int)(quadraKills: Int)(sightWardsBought: Int)(spell1Cast: Int)(spell2Cast: Int)(spell3Cast: Int)(spell4Cast: Int)(summonSpell1Cast: Int)(summonSpell2Cast: Int)(superMonsterKilled: Int)(team: Int)(teamObjective: Int)(timePlayed: Int)(totalDamageDealt: Int)(totalDamageDealtToChampions: Int)(totalDamageTaken: Int)(totalHeal: Int)(totalPlayerScore: Int)(totalScoreRank: Int)(totalTimeCrowdControlDealt: Int)(totalUnitsHealed: Int)(tripleKills: Int)(trueDamageDealtPlayer: Int)(trueDamageDealtToChampions: Int)(trueDamageTaken: Int)(turretsKilled: Int)(unrealKills: Int)(victoryPointTotal: Int)(visionWardsBought: Int)(wardKilled: Int)(wardPlaced: Int)(win: Bool) -> RawStats {
        
            return RawStats(assists: assists, barracksKilled: barracksKilled, championsKilled: championsKilled, combatPlayerScore: combatPlayerScore, consumablesPurchased: consumablesPurchased, damageDealtPlayer: damageDealtPlayer, doubleKills: doubleKills, firstBlood: firstBlood, gold: gold, goldEarned: goldEarned, goldSpent: goldSpent, item0: item0, item1: item1, item2: item2, item3: item3, item4: item4, item5: item5, item6: item6, itemsPurchased: itemsPurchased, killingSprees: killingSprees, largestCriticalStrike: largestCriticalStrike, largestKillingSpree: largestKillingSpree, largestMultiKill: largestMultiKill, legendaryItemsCreated: legendaryItemsCreated, level: level, magicDamageDealtPlayer: magicDamageDealtPlayer, magicDamageDealtToChampions: magicDamageDealtToChampions, magicDamageTaken: magicDamageTaken, minionsDenied: minionsDenied, minionsKilled: minionsKilled, neutralMinionsKilled: neutralMinionsKilled, neutralMinionsKilledEnemyJungle: neutralMinionsKilledEnemyJungle, neutralMinionsKilledYourJungle: neutralMinionsKilledYourJungle, nexusKilled: nexusKilled, nodeCapture: nodeCapture, nodeCaptureAssist: nodeCaptureAssist, nodeNeutralize: nodeNeutralize, nodeNeutralizeAssist: nodeNeutralizeAssist, numDeaths: numDeaths, numItemsBought: numItemsBought, objectivePlayerScore: objectivePlayerScore, pentaKills: pentaKills, physicalDamageDealtPlayer: physicalDamageDealtPlayer, physicalDamageDealtToChampions: physicalDamageDealtToChampions, physicalDamageTaken: physicalDamageTaken, playerPosition: playerPosition, playerRole: playerRole, quadraKills: quadraKills, sightWardsBought: sightWardsBought, spell1Cast: spell1Cast, spell2Cast: spell2Cast, spell3Cast: spell3Cast, spell4Cast: spell4Cast, summonSpell1Cast: summonSpell1Cast, summonSpell2Cast: summonSpell2Cast, superMonsterKilled: superMonsterKilled, team: team, teamObjective: teamObjective, timePlayed: timePlayed, totalDamageDealt: totalDamageDealt, totalDamageDealtToChampions: totalDamageDealtToChampions, totalDamageTaken: totalDamageTaken, totalHeal: totalHeal, totalPlayerScore: totalPlayerScore, totalScoreRank: totalScoreRank, totalTimeCrowdControlDealt: totalTimeCrowdControlDealt, totalUnitsHealed: totalUnitsHealed, tripleKills: tripleKills, trueDamageDealtPlayer: trueDamageDealtPlayer, trueDamageDealtToChampions: trueDamageDealtToChampions, trueDamageTaken: trueDamageTaken, turretsKilled: turretsKilled, unrealKills: unrealKills, victoryPointTotal: victoryPointTotal, visionWardsBought: visionWardsBought, wardKilled: wardKilled, wardPlaced: wardPlaced, win: win)
    }
    
    public static func decode(j: JSON) -> Decoded<RawStats> {
        return RawStats.create
        <*> j <| "assists"
        <*> j <| "barracksKilled"
        <*> j <| "championsKilled"
        <*> j <| "combatPlayerScore"
        <*> j <| "consumablesPurchased"
        <*> j <| "damageDealtPlayer"
        <*> j <| "doubleKills"
        <*> j <| "firstBlood"
        <*> j <| "gold"
        <*> j <| "goldEarned"
        <*> j <| "goldSpent"
        <*> j <| "item0"
        <*> j <| "item1"
        <*> j <| "item2"
        <*> j <| "item3"
        <*> j <| "item4"
        <*> j <| "item5"
        <*> j <| "item6"
        <*> j <| "itemsPurchased"
        <*> j <| "killingSprees"
        <*> j <| "largestCriticalStrike"
        <*> j <| "largestKillingSpree"
        <*> j <| "largestMultiKill"
        <*> j <| "legendaryItemsCreated"
        <*> j <| "level"
        <*> j <| "magicDamageDealtPlayer"
        <*> j <| "magicDamageDealtToChampions"
        <*> j <| "magicDamageTaken"
        <*> j <| "minionsDenied"
        <*> j <| "minionsKilled"
        <*> j <| "neutralMinionsKilled"
        <*> j <| "neutralMinionsKilledEnemyJungle"
        <*> j <| "neutralMinionsKilledYourJungle"
        <*> j <| "nexusKilled"
        <*> j <| "nodeCapture"
        <*> j <| "nodeCaptureAssist"
        <*> j <| "nodeNeutralize"
        <*> j <| "nodeNeutralizeAssist"
        <*> j <| "numDeaths"
        <*> j <| "numItemsBought"
        <*> j <| "objectivePlayerScore"
        <*> j <| "pentaKills"
        <*> j <| "physicalDamageDealtPlayer"
        <*> j <| "physicalDamageDealtToChampions"
        <*> j <| "physicalDamageTaken"
        <*> j <| "playerPosition"
        <*> j <| "playerRole"
        <*> j <| "quadraKills"
        <*> j <| "sightWardsBought"
        <*> j <| "spell1Cast"
        <*> j <| "spell2Cast"
        <*> j <| "spell3Cast"
        <*> j <| "spell4Cast"
        <*> j <| "summonSpell1Cast"
        <*> j <| "summonSpell2Cast"
        <*> j <| "superMonsterKilled"
        <*> j <| "team"
        <*> j <| "teamObjective"
        <*> j <| "timePlayed"
        <*> j <| "totalDamageDealt"
        <*> j <| "totalDamageDealtToChampions"
        <*> j <| "totalDamageTaken"
        <*> j <| "totalHeal"
        <*> j <| "totalPlayerScore"
        <*> j <| "totalScoreRank"
        <*> j <| "totalTimeCrowdControlDealt"
        <*> j <| "totalUnitsHealed"
        <*> j <| "tripleKills"
        <*> j <| "trueDamageDealtPlayer"
        <*> j <| "trueDamageDealtToChampions"
        <*> j <| "trueDamageTaken"
        <*> j <| "turretsKilled"
        <*> j <| "unrealKills"
        <*> j <| "victoryPointTotal"
        <*> j <| "visionWardsBought"
        <*> j <| "wardKilled"
        <*> j <| "wardPlaced"
        <*> j <| "win"
    }
}
```

**Comment by tonyd256** [comment] 2015-04-13 14:36
Haha, this is a very big model. I can see why you're hitting the limits of Swift's currying. Are there some submodels you feel you can make of these? A couple ideas I have are:

All the keys starting with "total" can be moved into a `Totals` model.
All of the "spells" can be moved into a `Spells` model.
All of the "items" can be moved into a `ItemStorage` model.

And in a similar fashion, group as many like things as you can into separate models. This might make things easier to work with too.

Another idea, if you are displaying all of these attributes to a user on some UI, maybe you can group these properties by the UI portion they will be displayed on. Say for instance you have a UI that has different views for the items the user had and a different view for the spells they used. Then you could group those into separate models. When it comes time to display the info, you can hand each view only the model it needs to display it's information.

**Comment by czeluff** [comment] 2015-04-13 16:24
Yep, that's one plan of attack. You could also make a case for having a struct that simply *alphabetizes* the properties: statsAF (all stats with variables names A-F), statsGM, etc.

The other plan: make RawStats only contain one 'let': the raw json itself, which can be extracted from a JSON enum via a switch statement. In decode, make a RawStats struct with one property, then wrap it in Decoded, and return it.

Then have all of the rest of these pieces of data - item0, item1, etc - be *computed* properties that simply *get* the value out of the JSON when requested. Yes, it moves very far away from what Argo is trying to accomplish with the Decoded type, the safety, the error messages, the guarantees of data existence, etc. But this is the *only* piece of data that has this issue, and I'm fine waiting for this Swift issue to go away.

**Comment by tonyd256** [comment] 2015-04-14 13:51
Ya, I think your second option isn't a bad idea for this. Unfortunately, Swift just can't handle so many properties on a model just yet. If you have a model that just contains the raw `JSON` value then you can make computed properties like you said. You can even use Argo in the computed properties to just get that one value out of the JSON.

**Comment by samritchie** [comment] 2015-04-28 10:06
In my testing the limit seems to be around 10-12 properties, which I don’t think is excessive on a model. The workaround from Swift 1.1 is broken on 1.2, and I’m struggling to work out what’s going on with the types.

Calling `MyType.create <^> j <| "property1" <*> j <| "property2"` returns a `Decoded<(remainder of curried create function)>` (e.g. `Decoded<(property3: String) -> MyType>`)

If I assign this to a local variable, based on my limited understanding of applicatives, I should be able to continue in a new expression with: `f <*> j <| "property3"`, however this doesn’t type check: `Could not find an overload for '<*>' that accepts the supplied arguments`

I’m not sure if my understanding is correct, or I’ve missed something obvious. At the moment I’m manually running the logic from `apply`, i.e.:

        switch f {
        case let .Success(box):
            return box.value <^> j <| "property3"
        case let .MissingKey(string):
            return .MissingKey(string)
        case let .TypeMismatch(string):
            return .TypeMismatch(string)
        }

but this is really clunky and there must be an easier way.

**Comment by tonyd256** [comment] 2015-04-28 14:33
@samritchie Thank you for bringing this to our attention. This issue seems to have started when switching to the `Decoded` type. This is most likely a bug with the compiler as we can reproduce this with `Array` but not with `Optional`. We'll be submitting a bug to Apple for this.

In the mean time, we found a workaround. If you add `_` to your curried parameters it should work. For instance:

```swift
static func create(prop1: String)(prop2: String)(_ prop3: String) -> String {
  return ""
}

let f = MyType.create <^> j <| "property1" <*> j <| "property2"
let x = f <*> j <| "property3"
```

Hope this helps. Going to keep this open for now. Please feel free to ask more questions about this workaround. @gfontenot is submitting a radar as we speak and will post the ID in here when he's done.

**Comment by samritchie** [comment] 2015-04-28 14:43
Thanks, that works. That was an odd one - I’m relieved to know I haven’t misunderstood applicatives as much as I thought.

**Comment by gfontenot** [comment] 2015-04-28 14:56
The radar I submitted is available on [Open Radar](http://www.openradar.me/20727035). The Swift team doesn't like dupes, so no point in that, but it's been reported.

**Comment by semka** [comment] 2015-05-08 19:20
Looks like workaround with `_` in curried parameters has limited functionality.
I have a `create` function like this:
```swift
public static func create(id: String?)
        (title: String?)
        (address: String?)
        (_ description: String?)
        (_ area: Double?)
        (_ price: Price?)
        (_ roomsNumber: Int?)
        (_ photoIds: [String]?)
        (_ contacts: [String]?) -> Realty 
```

And `decode` function:
```swift
    public static func decode(x: JSON) -> Decoded<J>? {
        let partial = Realty.create
            <^> x <|? "id"
            <*> x <|? "title"
            <*> x <|? "address"

        let partial2 = partial
            <*> x <|? "description"
            <*> x <|? "area"
            <*> x <|? "price"
        
        return partial2
            <*> x <|? "roomsNumber"
            <*> x <|? "photoIds"
            <*> x <|? "contacts"
    }
```

And on last partial clause I'm getting `Could not find an overload for '<*>' that accepts the supplied arguments` error.

**Comment by gfontenot** [comment] 2015-05-08 19:25
@semka the last two lines of your parser are parsing single values where your `create` function expects arrays. Replace those two with `<||?` and you should be good to go.

**Comment by semka** [comment] 2015-05-08 19:25
Me so stupid, thank you very much!

**Comment by gfontenot** [comment] 2015-09-04 18:53
I'm going to go ahead and close this. Feel free to continue to talk in here.

**Closed by gfontenot** 2015-09-04 18:53 UTC
