### ISSUE TITLE
Decoding a dictionary compiles, but fails to archive

### ISSUE THREAD

**Issue by zsszatmari** [thoughtbot/Argo#363] opened 2016-04-13 13:24 UTC
Hi!

Argo v3.0.1 with CocoaPods. Curry v2.2.0, Xcode 7.3, iOS target latest

```swift
struct MediaWithSize
{
    let width : Int
    let height : Int
    let urlString : String
}

struct MediaDetails
{
    let sizes : [String: MediaWithSize]
}

extension MediaDetails : Decodable
{
    static func decode(j : JSON) -> Decoded<MediaDetails>
    {
        return curry(MediaDetails.init)
            <^> (j <| "sizes" >>- [String : MediaWithSize].decode)
    }
}

extension MediaWithSize : Decodable
{
    static func decode(j : JSON) -> Decoded<MediaWithSize>
    {
        return curry(MediaWithSize.init)
            <^> j <| "width"
            <*> j <| "height"
            <*> j <| "source_url"
    }
}
```

  This compiles and runs just fine in simulator and device. But can't get it to Archive. On archiving, I only get (even with xcodebuild command line), the mysterious swiftc excited with error code 1.
  In particular, if I comment out the part with >>- (and return some bogus error instead), it archives fine.
  Any insights?
  Other than this, this lib is just awesome!

**Comment by gfontenot** [comment] 2016-04-13 13:30
my knee-jerk reaction is "oh no not this again". We've had issues with compiler optimizations before. I'd be interested to hear:

1. What happens if you turn off compiler optimizations for your release build
2. What happens if you change the syntax to use `.flatMap` instead of `>>-` (`(j <| "sizes").flatMap([String: MediaWithSize].decode)`)
3. What happens if you use `decodeObject` instead of `[String: MediaWithSize].decode` (and keep `>>-`)
4. What happens if you use `decodeObject` and `.flatMap`

**Comment by zsszatmari** [comment] 2016-04-13 13:52
0. Running in simulator but with Release mode: swiftc error code 1
1. Confirmed, turning off optimization for swift compiler for release and archive works.
2. Same error.
3. Worse: It fails with error code even without optimization
4. Same as 3.

**Comment by gfontenot** [comment] 2016-04-13 14:07
damn, that's what I was afraid of. Bummer that 3 and 4 don't work.

I think the way we've handled this in the past is to deconstruct `flatMap` into a single function that just takes the `Decoded<T>` type. Maybe something like:

```swift
decodeObjectFromDecoded<T: Decodable where T.DecodedType == T>(j: Decoded<JSON>) -> Decoded<[String: T]> {
  switch j {
    case let .Success(json): return [String: T].decode(json)
    case let .Failure(e): return .Failure(e)
  }
}
```

just spiked this out in here so syntax _might_ be off.

**Comment by zsszatmari** [comment] 2016-04-13 14:18
Umm, the provided function itself works, but how should I use it? I try something like ```<^> decodeObjectFromDecoded(j <| "sizes")``` but no success.

**Comment by gfontenot** [comment] 2016-04-19 16:29
@zsszatmari That seems like it should work. What's the error you're getting?

**Comment by zsszatmari** [comment] 2016-04-20 08:32
Hm! It works. I don't know, might have been a typo from my part on the other day? Thanks for helping out!

**Comment by gfontenot** [comment] 2016-04-20 16:53
Whew. That scared me for a bit. Glad it's working out for you! I'm going to go ahead and close this, but feel free to continue asking questions here or in a new thread if needed.

**Closed by gfontenot** 2016-04-20 16:53 UTC

**Comment by zsszatmari** [comment] 2016-04-20 16:55
Thanks, you are great! For now everything's perfect 👍

**Comment by mbrandonw** [comment] 2016-04-27 12:38
I just ran into this with `>>- [String:String].decode`. Curious if we know any reason this might be happening.

**Comment by mbrandonw** [comment] 2016-04-27 12:38
oh, and the `decodeObjectFromDecoded` fixed it, thanks @gfontenot!

**Comment by gfontenot** [comment] 2016-04-27 18:11
for more context:

We've had issues in the past with using `flatMap` or `>>-` and the optimizer. These issues _were_ gone, but it sure looks like they have resurfaced. If I have time/can remember I might try to reduce this down to a reproducible test case, but if anyone beats me to it I'd appreciate having a bug to track this.

**Comment by subdigital** [comment] 2016-07-03 13:46
Same happened to me, and the workaround provided was successful.  Thanks, @gfontenot!  This may warrant a page in the wiki, and it was tripping me up for quite a while.
