### ISSUE TITLE
Argo from Carthage stuck cloning/fetching runes.

### ISSUE THREAD

**Issue by NeoTeo** [thoughtbot/Argo#129] opened 2015-05-08 10:16 UTC
When following the instructions to install Argo using Carthage it hangs on getting the runes package.

```
> carthage update
*** Cloning Argo
*** Cloning Box
*** Cloning runes
```

It will sit there (left it overnight) until ^C
Running with the carthage update --verbose flag gives no additional info and after retrying I get this instead: 

```
> carthage update
*** Fetching Argo
*** Fetching Box
*** Fetching runes
```
I'm running Xcode 6.4 (6E14) command line tools but tried this with the 6.3 with the same result.

**Comment by gfontenot** [comment] 2015-05-08 14:45
Can you post your Cartfile?

**Comment by NeoTeo** [comment] 2015-05-08 14:51
It's a single line:

github "thoughtbot/Argo"

**Comment by gfontenot** [comment] 2015-05-08 14:54
I'm unable to reproduce here, unfortunately. What happens if you try bringing in Runes directly?

**Comment by NeoTeo** [comment] 2015-05-08 14:57
No problem: 
```
carthage update --verbose
*** Fetching runes
*** Downloading runes at "2.0.0: Precedence for President"
```

**Comment by MichaelMcGuire** [comment] 2015-05-08 17:16
Out of curiousity, which version of Carthage are you using @NeoTeo? I'm wondering if there might be a more [general issue](https://github.com/Carthage/Carthage/issues/445) with the newer version of Carthage.  I'm also experiencing some hangs with other packages.

**Comment by NeoTeo** [comment] 2015-05-08 19:32
It's version 0.7.0.

**Comment by gfontenot** [comment] 2015-05-12 14:09
It looks like these issues should be fixed in Carthage 0.7.2 or possibly in 0.7.3. Would y'all mind updating to verify?

**Comment by ikesyo** [comment] 2015-05-12 14:20
From what happening here, the issue is not about downloading binaries but cloning/fetching repositories. So this is fixed in [0.7.3](https://github.com/Carthage/Carthage/releases/tag/0.7.3).

**Comment by NeoTeo** [comment] 2015-05-13 11:40
Still broken in 0.7.3 (or at least it behaves the same)

**Comment by chrene** [comment] 2015-05-13 12:23
Updating to 0.7.3 didn't work for me either. Which version is the stable one?

**Comment by MichaelMcGuire** [comment] 2015-05-13 16:04
Looks like there are still [some] (https://github.com/Carthage/Carthage/issues/455) [issues](https://github.com/Carthage/Carthage/issues/445#issuecomment-101474729) with Carthage that will hopefully be resolved soon. I've gone back to 0.64 for now.

**Comment by gfontenot** [comment] 2015-05-13 16:09
Since this is actually a Carthage issue, and not an Argo (or Runes) issue, I'm going to close this, but feel free to continue the conversation. I'll post back in here when there is another fix available as well.

**Closed by gfontenot** 2015-05-13 16:09 UTC
