### ISSUE TITLE
Extracting Swift values from JSONValue?

### ISSUE THREAD

**Issue by king7532** [thoughtbot/Argo#73] opened 2015-03-04 03:06 UTC
I have 2 stupid questions, using the `comment.json` file from ArgoTests as sample JSON data:

```javascript
{
  "id": 6,
  "text": "Cool story bro.",
  "author": {
    "id": 1,
    "name": "Cool User"
  }
}
```
```swift
// Import JSONFileReader from ArgoTests
let jsonData: AnyObject? = JSONFileReader.JSON(fromFile: "comment")

let jsonComment = JSONValue.parse <^> jsonData!

let j = jsonComment!

let id: Int = j["id"]?.value()      // Error: Value of optional type 'Int?' not unwrapped"
let id: Int = j["id"]?.value()!     // Same error message as above
let text: String = j["text"]?.value()    // Ditto
```

1. How do I extract the Swift value for j["id"] and j["text"]?
`let id: Int = j["id"]?.value()    // Error: Value of optional type 'Int?' not unwrapped, did you mean to use ! or ?`  I would like id = 6.

2. How do I extract `j["author"]` as a Swift Dictionary<[String: JSONValue]>?  So I can then iterate over the keys and use my knowledge from question 1, above, to extract the JSONValue's.

I am using Swift 1.1 in Xcode 6.2 latest Beta (6C121).  Any help will be greatly appreciated.  Thank you

**Comment by gfontenot** [comment] 2015-03-04 03:14
- You should be using the `<|` operator for retrieving values from JSON:

```swift
let id: Int = j <| "id"
let text: String = j <| "text"
```

- You can get values of the type `[String: JSONValue]` with a simple custom parser:

```swift
func getDictionary(j: JSONValue) -> [String: JSONValue]? {
  switch j {
  case .let JSONObject(o): return o
  default: return .None
  }
}
```

That being said, we already have a built-in syntax for traversing dictionaries for nested keys:

```swift
let nested: String = j <| ["path", "to", "nested", "key"]
```

I highly suggest reading as much of the README as possible. I know it's long, but there's a ton of info in there.

I'm going to close this issue, but please feel free to keep asking questions if any of this still doesn't make sense.

**Closed by gfontenot** 2015-03-04 03:14 UTC

**Comment by tonyd256** [comment] 2015-03-04 03:35
As stated above, you should use the built in conventions for retrieving the data from the JSON. However, number 1 would be possible (although not recommended). You might want to read up on Optionals and their uses ... here is a little explanation to what you were seeing:

For that particular line: `let id: Int = j["id"]?.value()`, the `j["id"]` will return a `JSONValue?` which you can then optionally unwrap and call `value()`. `value()` returns the type you are requesting wrapped in an optional. In this case you are requesting an `Int` so it will return `Int?`.  You cannot assign an optional value to a non optional variable so it fails with that error message you are seeing. The solution would be to explicitly unwrap (always a bad idea) the optional to get the `Int`. However, throwing an `!` at the end of this statement doesn't help because the `j["id"]?` could still fail and return `.None`. To get directly at the value wrapped by the optional, the statement would look like this: `let id: Int = j["id"]!.value()!` ... again you shouldn't do this. Instead, use the value as an optional, `let id: Int? = j["id"]?.value()` or unwrap it using `if-let` syntax like so:

```
if let id = j["id"]?.value() as Int? {
  println(id)
}
```

That being said, still try to use Argo as intended as most of this value stuff will be deprecated in future versions.

**Comment by king7532** [comment] 2015-03-04 03:38
Believe me, I tried every combination of the `<|` operation to no avail.  I get the following compiler error when using `let id: Int = j <| "id"`

```
error: value of optional type 'Int?' not unwrapped; did you mean to use '!' or '?'?
        let id: Int = j <| "id"
                        ^
                               !
```

And when I try to add j? or j! I get the following compiler error:
```
error: operand of postfix '?' should have optional type; type is 'JSONValue'
        let id: Int = j? <| "id"
                      ~^
               
```

I did read the README and all 3 of the blog articles before posting this question.  Again, I am using:
* Xcode 6.2 Beta with Swift 1.1
* Runes - Master branch - commit: da9e74afbb994a5f68b59bb4eb4814e8619c836e
* Argo - swift-1.1 branch - commit: f31f5f3439d1ee59206e29cfaff4f79af077587c

**Comment by king7532** [comment] 2015-03-04 03:54
Thank you @tonyd256 and @gfontenot for the explanation, I now have a much better understanding.  One last question, can you explain this error message for:

```swift
if let text = j <| "text" {
            println(text)
        }
```

```
error: cannot invoke '<|' with an argument list of type '(JSONValue, StringLiteralConvertible)'
        if let text = j <| "text" {
                      ~~^~~~~~~~~
```
When the correct code is:
```swift
if let text = j <| "text" as String? {
    println(text)
}
```

**Comment by tonyd256** [comment] 2015-03-04 03:58
This is because the `<|` operator is relying on type inference meaning that if you need to tell it what type you want through a cast like in your second example. The error message is kind of misleading but basically Swift doesn't know what type you want so it's confused. By casting the variable or the result of the expression, you are telling the operator which type to try and return.
