### ISSUE TITLE
Argo 2, large objects, and ambiguous references.

### ISSUE THREAD

**Issue by nomothetis** [thoughtbot/Argo#235] opened 2015-09-21 22:11 UTC
An old problem seems to have resurfaced with a new head. We are breaking up large (more than 11 elements) objects into intermediate parts in order to appease the compiler. However, with the migration to Argo 2.0 and Swift 2, the compiler has a new complaint. Take this case (names made neutral):

```swift
public static func decode(j: JSON) -> Decoded<DataObject> {
    let firstPart =  DataObject.create
        <^> j <| "data1"
        <*> j <| "data2"
        <*> j <| "data3"
        <*> j <|? "data4"
        <*> j <|? "data5"
        
    let secondPart = firstPart
        <*> j <|? "data6"
        <*> j <|? "data7"
        <*> j <|? "data8"
        <*> j <|? "data9"
        <*> j <|? "data10"
        
    let thirdPart = secondPart
        <*> j <|? "data11"
        <*> j <|? "data12"
        <*> j <|? "data13"
        <*> j <|? "data14"
        <*> j <|? "data15"
            
    let fourthPart = thirdPart
        <*> j <|? "data16"
        <*> j <|? "data17"
        <*> j <|? "data18"
        <*> j <|? "data19"
        <*> j <|? "data20"
            
    return fourthPart
        <*> j <|? "data21"
        <*> j <|? "data22"
        <*> j <|? "data23"
        <*> j <|| "data24"
        <*> j <|| "data25"
        <*> j <|| "data26"
        <*> j <|? "data27"
}
```

The compiler complains in two spots (the second line of the `secondPart` assignment and the second line of the `thirdPart` assignment) about an "Ambiguous reference to member `<|?`". Does anyone know a way to get around this that doesn't involve breaking up the DataObject itself into multiple smaller objects that then get merged?

**Comment by paulyoung** [comment] 2015-09-21 22:13
@nomothetis it's nothing to do with `let thirdPart = firstPart` is it? Should be `let thirdPart = secondPart`.

**Comment by paulyoung** [comment] 2015-09-21 22:15
On second thought, it could be that you need to explicitly add Runes to your dependencies.

Runes was removed as a dependency of Argo in v2 so you'd need to add it to your Podfile, Cartfile, or as a submodule depending on what you use.

**Comment by tonyd256** [comment] 2015-09-21 22:17
if @paulyoung's suggestion ends up being just a typo in the example then I'm worried that the Swift 2 type inference has become a lot dumber. You shouldn't need Runes here. However, we added the capability for Argo's operators to return `Decoded` or `Optional`. I would hope the type inference could figure out which to use but maybe it's struggling.

**Comment by tonyd256** [comment] 2015-09-21 22:18
it would be a bit annoying but you could try to type all those intermediate part variables to see if you can force Swift's type inference to the correct type.

**Comment by tonyd256** [comment] 2015-09-21 22:19
you could also try `curry(init)` instead of the `create` function

**Comment by paulyoung** [comment] 2015-09-21 22:21
> You shouldn't need Runes here.

My mistake. The operators for `Optional` sound like a more likely candidate.

**Comment by nomothetis** [comment] 2015-09-21 22:22
Thanks for the quick response. To answer all questions:

1. No, it wasn't because of the typo (now fixed). I tried fixing the by reducing the number of groupings, and that's where the typo came from.

2. I'm not clear on what `curry(init)` means, but I'll look it up and give it a try. I'd rather not have to write the full partial type; it seems excessive and defeats the purpose. I too am worried about the type inferencer, though.

**Comment by paulyoung** [comment] 2015-09-21 22:26
By using [thoughtbot/Curry](https://github.com/thoughtbot/Curry) you don't need to write a `create` function and can replace `let firstPart =  DataObject.create` with let firstPart =  `curry(self.init)`

**Comment by neilpa** [comment] 2015-09-21 22:26
>  However, we added the capability for Argo's operators to return Decoded or Optional. I would hope the type inference could figure out which to use but maybe it's struggling.

This could also still be a problem. The compiler is still quite bad at return type inference (if that's the only thing which varies). In a few places in RAC we added explicit dummy type params to help it out to avoid varying strictly on return type.

**Comment by tonyd256** [comment] 2015-09-21 22:32
The optional returns on the Argo operators is new. I thought it might help but if it's the cause of this then I can remove it. If you are using carthage for dependencies, try using submodule mode and editing the local Argo source to remove that file. If you're using cocoapods you can edit the local Argo source that it downloads. If that fixes things let me know.

**Comment by nomothetis** [comment] 2015-09-21 22:33
I'll give that a go as well. Thanks.

**Comment by jshier** [comment] 2015-09-21 23:19
I ran into this, not because of a type inference issue, but because underlying errors were getting eaten up by the ambiguous reference error. In my case it was due to some enums that had explicit `decode` functions. Once I removed those, replacing them with just a conformance declaration, I was able to get some better error messages. I had some other, miscellaneous issues at the same time (Argo's new error handling), but eventually everything worked out and I didn't have to break any models into smaller parts.

**Comment by nomothetis** [comment] 2015-09-22 13:34
@jshier  —  thanks. The other suggestions didn't work, so maybe I'm running into a problem similar to yours. At this point the only two compilation errors I get are the ambiguous reference errors. I'll see if removing those methods brings to light any new issues.

**Comment by nomothetis** [comment] 2015-09-22 14:49
@tonyd256 I just tried explicitly adding the types of the intermediate values after removing the optional operators. Still didn't work. I also tried adding only *one* new `<*> j <|? "dataX"` expression, to see if it helped, and it didn't. I'm wondering at this point if I'm not making a mistake somewhere, but this compiled perfectly before the Swift 2.0 migration. :-(

**Comment by nomothetis** [comment] 2015-09-22 15:44
*WORKAROUND*

I got it to compile by doing two things. First, I added an `error` property to Decodable:

```swift
extension Decoded {
    var error:DecodeError? {
        get {
            switch self {
            case .Success(_): return nil
            case .Failure(let err): return err
            }
        }
    }
}
```

Second, I used it like so to modify the code:

```swift
public static func decode(j: JSON) -> Decoded<DataObject> {
    let firstPart =  DataObject.create
        <^> j <| "data1"
        <*> j <| "data2"
        <*> j <| "data3"
        <*> j <|? "data4"
        <*> j <|? "data5"

    guard let existingFirstPart = firstPart.value else {
        return Decoded.Failure(firstPart.error!)
    }

    let secondPart = existingFirstPart
        <^> j <|? "data6"
        <*> j <|? "data7"
        <*> j <|? "data8"
        <*> j <|? "data9"
        <*> j <|? "data10"

    guard let existingSecondPart = secondPart.value else {
        return Decoded.Failure(secondPart.error!)
    }

    let thirdPart = existingSecondPart
        <^> j <|? "data11"
        <*> j <|? "data12"
        <*> j <|? "data13"
        <*> j <|? "data14"
        <*> j <|? "data15"

    guard let existingThirdPart = thirdPart.value else {
        return Decoded.Failure(thirdPart.error!)
    }

    let fourthPart = existingThirdPart
        <^> j <|? "data16"
        <*> j <|? "data17"
        <*> j <|? "data18"
        <*> j <|? "data19"
        <*> j <|? "data20"

    guard let existingFourthPart = fourthPart.value else {
        return Decoded.Failure(fourthPart.error!)
    }

    return existingFourthPart
        <^> j <|? "data21"
        <*> j <|? "data22"
        <*> j <|? "data23"
        <*> j <|| "data24"
        <*> j <|| "data25"
        <*> j <|| "data26"
        <*> j <|? "data27"
}
```

I don't like it, but it compiles. I *really* dislike the `!`, but until we figure out what the issue is, it's relatively safe (since there should either be a value or an error). Thanks again for the help, everyone.

**Comment by tonyd256** [comment] 2015-09-22 17:20
hmm yes that is unfortunate. If you can give me a bit more so I can see this error on my computer I could try to work out a solution.

**Comment by amol-c** [comment] 2015-09-22 22:24
This is what we ended up doing for now.
Side Note: ` <^>` failed to compile for the first field and we had to use `<*>`. Not sure if there is any side-effect because of this, but everything seems to be working.

Not sure if there is a better way to get around this issue. I was getting back the Product in the ```static func decode(j: JSON) -> Decoded<Product>``` function instead of ```Decoded<Product>```, which worked fine in the previous version.

Hence, i had to covert to Decoded<Product> and return it.

Please advise if there is a better way to get around this.

```
struct Product: ProductData {
  let id: Int
  let name: String
  let rating: Float
  let numberOfRatings: Int?
  let author: Author
  let file: File?
  let isFree: Bool
  private let price: Float
  private let originalPrice: Float?
  let description: String?
  let thumbnails: [String]?
  let images: [String]?
  let grades: [Grade]?
  let subjects: [Subject]?
  let resourceTypes: [ResourceType]?
  private let isPurchased: Bool?
  private let isInWishlist: Bool?
  private let isInCart: Bool?
  private let isHardGood: Bool?

.............
..................

  init(id: Int, name: String, rating: Float, numberOfRatings: Int?, author: Author, file: File?, isFree: Bool, price: Float, originalPrice: Float?, description: String?, thumbnails: [String]?, images: [String]?, grades: [Grade]?, subjects: [Subject]?, resourceTypes: [ResourceType]?, isPurchased: Bool?, isInWishlist: Bool?, isInCart: Bool?, isHardGood: Bool?) {
    self.id = id
    self.name = name
    self.rating = rating
    self.numberOfRatings = numberOfRatings
    self.author = author
    self.file = file
    self.isFree = isFree
    self.price = price
    self.originalPrice = originalPrice
    self.description = description
    self.thumbnails = thumbnails
    self.images = images
    self.grades = grades
    self.subjects = subjects
    self.resourceTypes = resourceTypes
    self.isPurchased = isPurchased
    self.isInWishlist = isInWishlist
    self.isInCart = isInCart
    self.isHardGood = isHardGood
  }
}

............
...............

extension Product: Decodable {
  static func create(id: Int)(name: String)(rating: Float)(numberOfRatings: Int?)(author: Author)(file: File?)(isFree: Bool)(price: Float)(originalPrice: Float?)(description: String?)( thumbnails: [String]?)(images: [String]?)(grades: [Grade]?)(subjects: [Subject]?)(resourceTypes: [ResourceType]?)(isPurchased: Bool?)(isInWishlist: Bool?)(isInCart: Bool?)(isHardGood: Bool?) -> Product {
    return Product(id: id,
      name: name,
      rating: rating,
      numberOfRatings: numberOfRatings,
      author: author,
      file: file,
      isFree: isFree,
      price: price,
      originalPrice: originalPrice,
      description: description,
      thumbnails: thumbnails,
      images: images,
      grades: grades,
      subjects: subjects,
      resourceTypes: resourceTypes,
      isPurchased: isPurchased,
      isInWishlist: isInWishlist,
      isInCart: isInCart,
      isHardGood: isHardGood)
  }

  static func decode(j: JSON) -> Decoded<Product> {
    let firstPart = Product.create
      <*> j <| "id"
      <*> j <| "name"
      <*> j <| "rating"
      <*> j <|? "votes"
      <*> j <| "author"

    let secondPart = firstPart
      <*> j <|? "file"
      <*> j <| "isFree"
      <*> j <| "price"
      <*> j <|? "originalPrice"
      <*> j <|? "description"

    let thirdPart = secondPart
      <*> j <||? "thumbnails"
      <*> j <||? "images"
      <*> j <||? "grades"
      <*> j <||? "subjectAreas"
      <*> j <||? "resourceTypes"

    let fourthPart = thirdPart
      <*> j <|? "isPurchased"
      <*> j <|? "isInWishlist"
      <*> j <|? "isInCart"
      <*> j <|? "isHardGood"

    var decodedProduct: Decoded<Product> = Decoded<Product>.Failure(.MissingKey("This is temporary fix and currently we have no way to identify, what went wrong until we find a fix for long list of functions"))
    if let fourthPart = fourthPart {
      decodedProduct = Decoded<Product>.Success(fourthPart)
    }

    return decodedProduct
  }
}
```


I was able to use method partially as suggested by @nomothetis, as i was getting back the ```Product``` instead of `Decoded<Product>`

**Comment by tonyd256** [comment] 2015-09-22 22:40
Would you be able to post the code for the other models mentioned here ... Author, File, Grade, Subject, ResourceType etc. I think there might be an easier solution but it's hard to mess around with this without all the code.

**Comment by tonyd256** [comment] 2015-09-22 22:47
My assumption is that you are also importing `Runes` into this file. If you are, then the `Optional` implementations for the Runes operators, `<*>`, and the Argo operators, `<|` etc, are available here.That means that unless you cast something to either `Decoded` or `Optional` it will be ambiguous which to use.

You say that `<^>` failed to compile when used for the first property. I'm willing to bet it's because it didn't know which version of that operator to use, `Decoded` or `Optional`. The reason `<*>` worked instead is because Swift will cast a non-optional to an optional automatically where as it won't do that for `Decoded`. So because it can only do that for `Optional`, that forced Swift to use all the `Optional` versions of those operators.

If you are importing Runes above, what happens when you remove it, change the first property back to `<^>` and replace `let forthPath =` with `return`. Also comment out the whole `var decodedProduct` stuff at the end.

**Comment by nomothetis** [comment] 2015-09-23 02:14
Sorry all; I tried to create a standalone project, but for reasons that are
unclear to me, Carthage stopped working. Once I resolve that, I'll post it
here.

**Comment by amol-c** [comment] 2015-09-23 14:09
@tonyd256 
Sorry, if i wasn't clear before. If i use <^>, i end up getting the error as seen in the screenshot below. But, if i use ```<*>``` along with the return using ```var decodedProduct ``` stuff, it seems to work fine and i don't see the error ``` Expression was too complex ... ```

![screen shot 2015-09-23 at 10 11 27 am](https://cloud.githubusercontent.com/assets/2050256/10047170/d3aa13c8-61da-11e5-8ca9-a4d3dbd1251f.png)

Here is the gist for all the Models referred by and including Product.swift
https://gist.github.com/amol-c/89a3dffe9051ef8b8e93

**Comment by nomothetis** [comment] 2015-09-23 14:24
Here's my own project. The only relevant file is `ServerContactFull.swift`, but I wanted to have a full project with carthage included to illustrate the problem.

https://github.com/nomothetis/ArgoIssue

Note: the workaround I posted above didn't work for this project. Not sure why.

**Comment by amol-c** [comment] 2015-09-23 14:51
@nomothetis Whats the Xcode Version are you using ?

**Comment by nomothetis** [comment] 2015-09-23 17:30
Xcode 7.0.

**Comment by tonyd256** [comment] 2015-09-23 17:32
Thanks guys, I'll pull down this code and play around with it on my end and get back to you.

**Comment by tonyd256** [comment] 2015-09-23 18:45
ah ok ... I think I figured it out. There is this super lame bug with Swift that we discovered. I can never find the issue again but I will now refer to it as the Super Lame Underscore Issue with Partial Application or SLUIPA (pronounced slew-pa)

Anyways, you need to add an underscore before the parameter for each parameter after the split occurs. So in your instance, every parameter after and including `callCount` (also `file` and `data6` from the examples above. I also needed to exchange `NSDate` for `String` in your code because `NSDate` had not been made `Decodable` yet. But you can do that in your project and it would work. Here is what I needed to change:

```swift
static func create(contactId:Int64)
        (firstName:String)
        (lastName:String)
        (isBuyerLead:Bool?)
        (isSellerLead:Bool?)
        (_ callCount:Int?)
        (_ lastCallDate:String?)
        (_ emailCount:Int?)
        (_ lastEmail:String?)
        (_ textCount:Int?)
        (_ lastDateText:String?)
        (_ registerDate:String?)
        (_ bestPhone:String?)
        (_ autoEAlertEnabled:Bool?)
        (_ searchTotal:Int64?)
        (_ city:String?)
        (_ state:String?)
        (_ zipCode:String?)
        (_ showStreet:Bool?)
        (_ description:String?)
        (_ roleId:Int64?)
        (_ tenantId:Int?)
        (_ photoLink:String?)
        -> ServerContactFull {
          return ServerContactFull(contactId: contactId, firstName: firstName, lastName: lastName, isBuyerLead: isBuyerLead, isSellerLead: isSellerLead, callCount: callCount, lastCallDate: lastCallDate, emailCount: emailCount, lastEmail: lastEmail, textCount: textCount, lastDateText: lastDateText, registerDate: registerDate, bestPhone: bestPhone, autoEAlertEnabled: autoEAlertEnabled, searchTotal: searchTotal, city: city, state: state, zipCode: zipCode, showStreet: showStreet, description: description, roleId: roleId, tenantId: tenantId, photoLink: photoLink)
    }
```

Note the underscores.

**Comment by amol-c** [comment] 2015-09-23 20:25
@tonyd256 Thanks for the above snippet. I had included Argo and Runes, which caused the conflict as you mentioned.
Also, the above solution worked after breaking down into smaller chunks, my guess is its because of the complex type. I am attaching the code for future reference.

```
  static func decode(j: JSON) -> Decoded<Product> {
    let firstPart = Product.create
      <^> j <| "id"
      <*> j <| "name"
      <*> j <| "rating"
    let secondPart = firstPart

      <*> j <|? "votes"
      <*> j <| "author"
      <*> j <|? "file"
    let thirdPart = secondPart

      <*> j <| "isFree"
      <*> j <| "price"
      <*> j <|? "originalPrice"
      <*> j <|? "description"
    let fourthPart = thirdPart
      <*> j <||? "thumbnails"
      <*> j <||? "images"
      <*> j <||? "grades"
    let fifthPart = fourthPart
      <*> j <||? "subjectAreas"
      <*> j <||? "resourceTypes"
      <*> j <|? "isPurchased"
    return fifthPart
      <*> j <|? "isInWishlist"
      <*> j <|? "isInCart"
      <*> j <|? "isHardGood"
  }
```

**Comment by paulyoung** [comment] 2015-09-23 20:48
Super Lame Underscore Issue with Partial Application :point_right: https://github.com/thoughtbot/Argo/issues/106#issuecomment-97085787

**Comment by tonyd256** [comment] 2015-09-23 21:54
ah yes, thanks @paulyoung for finding that!

**Comment by tonyd256** [comment] 2015-09-23 21:57
@amol-c glad it worked for you! With Swift 2 you don't need to write your own `create` functions anymore. You can use the Curry library to wrap the `init` like this: `curry(self.init)` instead of `Product.create`. Then you can delete the whole `create` function. Once https://github.com/thoughtbot/Curry/pull/10 happens :fingers_crossed: there will be a curry function that will work with this huge class.

Closing this for now. Feel free to comment on here if you have more questions or create a new issue for something else.

**Closed by tonyd256** 2015-09-23 21:57 UTC

**Comment by marcel** [comment] 2015-09-30 06:22
My observation is that if the struct has *more* than 15 properties all of a sudden the 16th property triggers the Ambiguous reference error. It's not the issue of the expression being too complex. You can split it all out into individual assignments. I verified in two separate unrelated structs that going from 15 to 16 triggered the error.

In Scala there is a limitation to the number of arguments a case class constructor can have (23). I don't know if there is some such limit at play here. Googling for swift and 15/16 didn't reveal anything. Figured I'd mention it.

**Comment by tonyd256** [comment] 2015-09-30 17:31
@marcel The code I tested above has more than 16 parameters and I didn't see this issue. Would you be able to post your code? I'm curious why you're see this issue.

**Comment by paulyoung** [comment] 2015-09-30 18:59
I've run into this issue with far less than 15 parameters too, where the decoding was more customized.

**Comment by marcel** [comment] 2015-09-30 22:59
@tonyd256 sure,  I cut a branch and committed a couple examples: https://github.com/marcel/Twitter/commit/44d96fb8e9410b84b9b003fc54c2fd16685cb568

I'm running Xcode 7.0 beta 6 (7A192o) and Swift 2.0 (swiftlang-700.0.59 clang-700.0.72) on OS 10.11 Beta (15A278b).

In both cases you should see the "Ambiguous reference" error appearing on the first instance of "<|" in each decode method.

You can do at least two things to make the error go away:

1) Delete the lines tagged "Delete me" (one for the property declaration and one for the json attribute extractor). With those lines gone the error then goes away.

2) Leave that one in/put it back and comment out any other property declaration/json attribute extractor pair and see the error go away also.

You can move the last or any other parameter into a different position or break up the grouping of the incremental lets into any size and it will always show the error if there are 16 total attributes and it won't if there are 15.

I have not created a bespoke 16 property create factory as you did above with explicit underscores. That may afford a work around to whatever I'm observing. I wanted to avoid having to specify the mapping three times. 

@paulyoung right, this error pops up regardless of the number of total properties simply if there is a type mismatch error in the declarations. If the declared property has different optionality or cardinality from what the extractor specified all such errors manifest at compile time as this ambiguous reference error even with just a single property let alone 16. Any number of underlying errors are swallowed and manifest as this ambiguous reference error.

What was notable though to me about what I'm observing here is that I'm pretty confident I don't have one of those basic type mismatch errors. Something else seems at play here.

**Comment by thbaja** [comment] 2015-10-07 14:01
Encountered this as well.

Went from from 14 to 15 properties in Swift 2.0 (in 1.2 it was for above 11 properties for me) and then used the splitting up solution. But this gave me "ambiguous use of operator '<|?'". 
If it's optional or not doesn't seem to matter.

Removing Runes import solved it as explained by @tonyd256 above.

**Comment by charliebartel** [comment] 2015-10-09 20:37
@tonyd256  I'm seeing the same issue described by @marcel above. My setup is the same.

**Comment by tonyd256** [comment] 2015-10-09 21:58
Aha! Ok so this is happening because the Curry library can only handle 15 parameters. Once https://github.com/thoughtbot/Curry/pull/10 gets merged then it will work.

**Comment by charliebartel** [comment] 2015-10-09 22:22
@tonyd256 Thanks for the update!

**Comment by gfontenot** [comment] 2015-10-11 18:53
Curry 1.3.0 is now available, and should help with this issue.

**Comment by charliebartel** [comment] 2015-10-12 14:55
@gfontenot 'pod outdated' is not seeing Curry version 1.3.0. 
The pod spec on cocoapods.org is still pointing to version 1.2 as the latest. Can you submit the new pod spec to trunk? thanks!

**Comment by gfontenot** [comment] 2015-10-12 17:05
@charliebartel Yeah, sorry about that. CocoaPods was giving me trouble. I've pushed it now.

**Comment by charliebartel** [comment] 2015-10-12 18:13
After upgrading my pod to Curry version 1.3.0 the model decodes as expected with 15+ parameters.  I think we can consider this issue resolved.  
Thanks @gfontenot @tonyd256 @marcel
